spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server.port: 8082
thunderstorm:
  aisSourceUrl: https://coast.noaa.gov/htdata/CMSP/AISDataHandler/2021/
  sourceDataFileLocation: ./data/
  sourceDataFileUnzipLocation: ./data/unzip